// SPDX-License-Identifier: Apache-2.0
//
// ROS 2 wrapper around Copilot C99 generated by Ogma for REQ-ALT-01 (ADR 0002).
// Subscribes to PX4 vehicle_local_position with SensorDataQoS [G 3.6, 4.5] and
// publishes a timestamped MonitorVerdict on every Copilot step (ADR 0002 rule 2-3).
#include <atomic>
#include <cstdint>

#include <rclcpp/rclcpp.hpp>
#include <px4_msgs/msg/vehicle_local_position.hpp>
#include <px4_ros2/utils/message_version.hpp>
#include <guara_msgs/msg/monitor_verdict.hpp>

extern "C" {
#include "copilot.h"
}

// Copilot extern stream (generated Copilot.hs: `extern "input_signal"`).
float input_signal = 0.0F;

namespace
{
std::atomic<bool> g_handler_fired{false};

void publishPending(rclcpp::Publisher<guara_msgs::msg::MonitorVerdict>::SharedPtr pub,
  const rclcpp::Time & recv, double processing_s, std::uint64_t step, bool complete)
{
  guara_msgs::msg::MonitorVerdict msg;
  const std::int64_t ns = recv.nanoseconds();
  msg.stamp.sec = static_cast<std::int32_t>(ns / 1000000000LL);
  msg.stamp.nanosec = static_cast<std::uint32_t>(ns % 1000000000LL);
  msg.monitor_id = "REQ-ALT-01";
  msg.monitor_class = guara_msgs::msg::MonitorVerdict::CLASS_SWITCH;
  msg.action = guara_msgs::msg::MonitorVerdict::ACTION_HOLD;
  msg.violated = g_handler_fired.load();
  msg.inputs_complete = complete;
  msg.step = step;
  msg.processing_s = processing_s;
  pub->publish(msg);
}

}  // namespace

extern "C" void handlerAltitudeBelowCeiling(void)
{
  g_handler_fired.store(true);
}

class AltitudeMonitorNode : public rclcpp::Node
{
public:
  AltitudeMonitorNode()
  : Node("guara_monitors")
  {
    const auto qos = rclcpp::SensorDataQoS();
    const std::string topic = "fmu/out/vehicle_local_position" +
      px4_ros2::getMessageNameVersion<px4_msgs::msg::VehicleLocalPosition>();
    pub_ = create_publisher<guara_msgs::msg::MonitorVerdict>(
      "/guara/monitors/verdict", rclcpp::QoS(32).best_effort());
    sub_ = create_subscription<px4_msgs::msg::VehicleLocalPosition>(
      topic, qos, [this](const px4_msgs::msg::VehicleLocalPosition & msg) {onSample(msg);});
  }

private:
  void onSample(const px4_msgs::msg::VehicleLocalPosition & msg)
  {
    const rclcpp::Time t_recv = now();
    input_signal = msg.z;
    g_handler_fired.store(false);
    step();
    const rclcpp::Time t_pub = now();
    publishPending(pub_, t_recv, (t_pub - t_recv).seconds(), step_, msg.z_valid);
    ++step_;
  }

  rclcpp::Subscription<px4_msgs::msg::VehicleLocalPosition>::SharedPtr sub_;
  rclcpp::Publisher<guara_msgs::msg::MonitorVerdict>::SharedPtr pub_;
  std::uint64_t step_{0};
};

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<AltitudeMonitorNode>());
  rclcpp::shutdown();
  return 0;
}
